# ========================================
# КОНФИГУРАЦИЯ ESPHOME ДЛЯ КУХОННОЙ ВЫТЯЖКИ
# ========================================
# Этот файл настраивает ESP32 для управления кухонной вытяжкой
# через UART протокол с инвертированным сигналом

esphome:
  # Основное имя устройства в ESPHome
  name: kitchen-hood-emulator
  # Дружественное имя для отображения в интерфейсе
  friendly_name: "ESP32 Kitchen Hood"
  
  # Действия при загрузке ESP32
  on_boot:
    # Приоритет 800: отключение сна WiFi для стабильной работы
    - priority: 800
      then:
        - lambda: |-
            WiFi.setSleep(false);

    # Приоритет -100: привязка переключателей Home Assistant к компоненту вытяжки
    # Выполняется после инициализации всех компонентов
    - priority: -100
      then:
        - lambda: |-
            if (kitchen_hood::KitchenHood::instance) {
              // Привязываем переключатель подсветки к компоненту вытяжки
              kitchen_hood::KitchenHood::instance->bind_light_switch(id(light_switch));
              // Привязываем переключатель звука к компоненту вытяжки
              kitchen_hood::KitchenHood::instance->bind_sound_switch(id(sound_switch));
            }
        - logger.log: "Boot completed"  
        
# ========================================
# НАСТРОЙКИ ESP32
# ========================================
esp32:
  # Тип платы ESP32
  board: esp32dev
  # Используем Arduino framework для совместимости
  framework:
    type: arduino

# ========================================
# НАСТРОЙКИ WI-FI ПОДКЛЮЧЕНИЯ
# ========================================
wifi:
  # SSID вашей Wi-Fi сети
  ssid: ""
  # Пароль от Wi-Fi сети
  password: ""
  
  # Статический IP адрес для стабильного подключения
  manual_ip:
    static_ip: 192.168..      # Фиксированный IP адрес ESP32
    gateway: 192.168..1          # IP адрес роутера (шлюза)
    subnet: 255.255.255.0           # Маска подсети
  
  # Точка доступа для настройки при отсутствии Wi-Fi
  ap:
    ssid: "ESP32_KitchenHood"       # Имя точки доступа
    password: ""           # Пароль точки доступа
  
  fast_connect: true
  power_save_mode: none 
  reboot_timeout: 0s    
  
# ========================================
# НАСТРОЙКИ API ДЛЯ HOME ASSISTANT
# ========================================
api:
  # Шифрование API для безопасной связи с Home Assistant
  encryption:
    key: 
  # Отключаем таймаут перезагрузки для API
  reboot_timeout: 0s    

# ========================================
# НАСТРОЙКИ OTA (ОБНОВЛЕНИЕ ПО ВОЗДУХУ)
# ========================================
ota:
  platform: esphome                 # Используем ESPHome для OTA
  password: ""                      # Пароль для OTA (пустой = без пароля)

safe_mode:
  reboot_timeout: 0s   # новый отдельный компонент вместо ota.safe_mode
  


# ========================================
# MQTT
# ======================================== 
mqtt:
  broker: "192.168.."
  username: 
  password: 
  topic_prefix: kitchenhood/esp32
  discovery: false  # Отключает авто-регистрацию в HA через MQTT
  reboot_timeout: 0s  

# ========================================
# НАСТРОЙКИ UART ДЛЯ СВЯЗИ С ВЫТЯЖКОЙ
# ========================================
uart:
  # Пин для передачи данных (TX)
  tx_pin:
    number: GPIO13                   # Используем GPIO13 для UART TX
    inverted: false                  # Инверсия сигнала отключена (управляется в коде)
  baud_rate: 500                    # Скорость UART: 500 бод (медленно, но надежно)
  id: uart_bus                      # Идентификатор UART шины для компонентов

# ========================================
# РЕГИСТРАЦИЯ КОМПОНЕНТА КУХОННОЙ ВЫТЯЖКИ
# ========================================
# Основной компонент для управления кухонной вытяжкой
kitchen_hood:
  uart_id: uart_bus                 # Используем настроенную UART шину

# ========================================
# ВНЕШНИЕ КОМПОНЕНТЫ
# ========================================
# Подключаем кастомный компонент kitchen_hood из локальной папки
external_components:
  - source:
      type: local                   # Локальный источник компонентов
      path: custom_components       # Путь к папке с кастомными компонентами
    components: [kitchen_hood]      # Список подключаемых компонентов

# ========================================
# НАСТРОЙКИ ЛОГГИРОВАНИЯ
# ========================================
# Логгер для отладки и мониторинга работы системы
logger:
  #baud_rate: 0
  level: DEBUG    

# ========================================
# ПОДКЛЮЧЕНИЕ ШИНЫ i2c
# ========================================
i2c:
  sda: GPIO21
  scl: GPIO22
  scan: true
  id: bus_a
  
  
sensor:
  - platform: bmp085
    i2c_id: bus_a
    address: 0x77
    temperature:
      name: "BMP180 Temperature"
      accuracy_decimals: 2      
    pressure:
      name: "BMP180 Pressure"
      unit_of_measurement: "mmHg"
      accuracy_decimals: 2
      filters:
        - lambda: |-
            return x * 0.75006;
    update_interval: 5s            


  - platform: htu21d
    model: htu21d
    i2c_id: bus_a
    address: 0x40
    temperature:
      name: "SHT21 Temperature"
      accuracy_decimals: 2
    humidity:
      name: "SHT21 Humidity"
      accuracy_decimals: 2
    update_interval: 5s     

    

# ========================================
# КНОПКИ УПРАВЛЕНИЯ СКОРОСТЬЮ МОТОРА
# ========================================
# Кнопки для выбора скорости работы кухонной вытяжки
# Скорость 0 = выключен, 1 = низкая, 2 = средняя, 3 = максимальная
button:
  # Кнопка "Мотор выключен" (скорость 0)
  - platform: template
    name: "Motor Speed 0"           # Имя кнопки в Home Assistant
    on_press:                       # Действие при нажатии
      then:
        - lambda: |-
            if (kitchen_hood::KitchenHood::instance) {
              // Вызываем метод установки скорости 0 (выключен)
              kitchen_hood::KitchenHood::instance->press_motor_speed(0);
            }

  # Кнопка "Низкая скорость" (скорость 1)
  - platform: template
    name: "Motor Speed 1"           # Имя кнопки в Home Assistant
    on_press:                       # Действие при нажатии
      then:
        - lambda: |-
            if (kitchen_hood::KitchenHood::instance) {
              // Вызываем метод установки скорости 1 (низкая)
              kitchen_hood::KitchenHood::instance->press_motor_speed(1);
            }

  # Кнопка "Средняя скорость" (скорость 2)
  - platform: template
    name: "Motor Speed 2"           # Имя кнопки в Home Assistant
    on_press:                       # Действие при нажатии
      then:
        - lambda: |-
            if (kitchen_hood::KitchenHood::instance) {
              // Вызываем метод установки скорости 2 (средняя)
              kitchen_hood::KitchenHood::instance->press_motor_speed(2);
            }

  # Кнопка "Максимальная скорость" (скорость 3)
  - platform: template
    name: "Motor Speed 3"           # Имя кнопки в Home Assistant
    on_press:                       # Действие при нажатии
      then:
        - lambda: |-
            if (kitchen_hood::KitchenHood::instance) {
              // Вызываем метод установки скорости 3 (максимальная)
              kitchen_hood::KitchenHood::instance->press_motor_speed(3);
            }

# ========================================
# ПЕРЕКЛЮЧАТЕЛИ ПОДСВЕТКИ И ЗВУКА
# ========================================
# Переключатели для управления дополнительными функциями вытяжки
switch:
  # Переключатель подсветки кухонной вытяжки
  - platform: template
    name: "Light"                   # Имя переключателя в Home Assistant
    id: light_switch                # Уникальный идентификатор для привязки
    turn_on_action:                 # Действие при включении подсветки
      - lambda: |-
          if (kitchen_hood::KitchenHood::instance) {
            // Включаем подсветку через компонент вытяжки
            kitchen_hood::KitchenHood::instance->set_light(true);
          }
    turn_off_action:                # Действие при выключении подсветки
      - lambda: |-
          if (kitchen_hood::KitchenHood::instance) {
            // Выключаем подсветку через компонент вытяжки
            kitchen_hood::KitchenHood::instance->set_light(false);
          }

  # Переключатель звукового сопровождения
  - platform: template
    name: "Sound"                   # Имя переключателя в Home Assistant
    id: sound_switch                # Уникальный идентификатор для привязки
    turn_on_action:                 # Действие при включении звука
      - lambda: |-
          if (kitchen_hood::KitchenHood::instance) {
            // Включаем звуковое сопровождение через компонент вытяжки
            kitchen_hood::KitchenHood::instance->set_sound(true);
          }
    turn_off_action:                # Действие при выключении звука
      - lambda: |-
          if (kitchen_hood::KitchenHood::instance) {
            // Выключаем звуковое сопровождение через компонент вытяжки
            kitchen_hood::KitchenHood::instance->set_sound(false);
          }